# Generated by Django 4.2.16 on 2024-09-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0002_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('othor', 'Othor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
