# Generated by Django 4.2.16 on 2024-10-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0005_alter_userdetail_gender_playsession_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playsession',
            name='end_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
