# Generated by Django 4.2.16 on 2024-10-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0006_alter_playsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgames',
            name='image',
            field=models.ImageField(upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
