# Generated by Django 4.2.16 on 2024-10-15 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0007_alter_boardgames_image_alter_payments_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playsession',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
