# Generated by Django 4.2.16 on 2024-10-16 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0009_boardgames_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='board_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boardgame.boardgames'),
        ),
    ]
