# Generated by Django 4.2.16 on 2024-10-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0010_reservation_board_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playsession',
            name='price_per_player',
        ),
    ]
