# Generated by Django 4.2.16 on 2024-10-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0011_remove_playsession_price_per_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playsession',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
